### ISSUE TITLE
spring-cloud-sleuth-otel won't instrument RabbitMQ

### ISSUE THREAD

**Issue by tochenliqun** [spring-projects-experimental/spring-cloud-sleuth-otel#118] opened 2022-07-26 17:59 UTC
**Describe the bug**

For RabbitMQ (AMQP), the spring-cloud-sleuth-brave can instrument the messages by default. but spring-cloud-sleuth-otel won't instrument it ( it DOES for Kafka though) atomically. could you investigate and add this for RabbitMQ as well?

```xml
        <!-- Sleuth with OpenTelemetry tracer implementation -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.cloud</groupId>
                    <artifactId>spring-cloud-sleuth-brave</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- This dependency adds OTel support -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-otel-autoconfigure</artifactId>
        </dependency>
```xml

**Sample**

I created a demo project here (https://github.com/codebycase/demo), you can see the README.md and run DemoApplication to test out.

**Comment by Michal-Kucera** [comment] 2022-08-02 07:24
Seems to be a duplicate of https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/issues/100

**Comment by marcingrzejszczak** [comment] 2022-08-17 12:54
Yeah that's a duplicate of #100 . I'll copy the reproducer information from here to that issue

**Closed by marcingrzejszczak** 2022-08-17 12:54 UTC
